name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - "webapp/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Link validation
      - name: Check for broken links
        uses: peter-evans/link-checker@v1
        with:
          args: -r webapp/**/*.html

      # HTML/CSS validation using html-validate
      - name: Validate HTML
        run: |
          npm install --global html-validate
          html-validate webapp/**/*.html

      # Accessibility checks with pa11y
      - name: Accessibility Check
        run: |
          npm install --global pa11y http-server
          http-server webapp/ -p 8080 &
          sleep 10 # wait for the server to start
          pa11y http://localhost:8080/index.html --timeout 90000 # 90 seconds

      # Performance audits with Lighthouse
      - name: Lighthouse Performance Audit
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: "http://portfolioappservice.azurewebsites.net" # Replace with the actual URL of your web application

      # Deployment to Azure Web App
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "portfolioAppService" # Ensure this matches the name of your Azure App Service
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "webapp"
