name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main # Replace 'main' with your branch name if it's different
    paths:
      - 'webapp/**' # Assuming 'webapp' is the directory where your website files are located

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # If your web application has build steps, insert them here.
      # Example for a Node.js app (remove if not applicable):
      # - name: Build
      #   run: |
      #     npm install
      #     npm run build
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'portfolioAppService' # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'webapp' # The path to your web application's build directory
