name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - "webapp/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Example step for link validation
      - name: Check for broken links
        uses: peter-evans/link-checker@v1
        with:
          args: -r webapp/**/*.html

      # Example step for HTML/CSS validation using W3C Validator
      - name: Validate HTML/CSS
        run: |
          docker pull validator/validator
          docker run -v ${PWD}:/workspace validator/validator /workspace/webapp/**/*.html

      # Accessibility checks with pa11y
      - name: Accessibility Check
        run: |
          npm install -g pa11y
          pa11y webapp/index.html

      # Performance audits with Lighthouse
      - name: Lighthouse Performance Audit
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            http://localhost/webapp/index.html
          budgetPath: './budget.json'

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "portfolioAppService"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "webapp"
