name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - "webapp/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Link validation
      - name: Check for broken links
        uses: peter-evans/link-checker@v1
        with:
          args: -r webapp/**/*.html

      # HTML validation using html-validate
      - name: Validate HTML
        run: |
          npm install --global html-validate
          html-validate webapp/**/*.html

      # Deployment to Azure Web App
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "portfolioAppService" # Ensure this matches the name of your Azure App Service
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "webapp"
