name: Deploy to Azure Web App

on:
  push:
    branches:
      - main # Replace 'main' with your branch name if it's different
    paths:
      - "webapp/**" # Triggers the workflow only on changes within the 'webapp' directory

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # If you have any build steps, include them here
      # For a static site with just HTML/CSS/JavaScript, you may not need any build steps

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "portfolioAppService" # Replace with your actual Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "webapp" # The path to the directory containing your webapp files
